fix configure-values.sh missing AZURE_SUBSCRIPTION_ID (#342)
* Update configure-values.sh

chmod +x ./configure-values.sh && ./configure-values.sh ${CLUSTER_NAME} ${RG} karpenter-sa karpentermsi
Configuring karpenter-values.yaml for cluster karpenter in resource group karpenter ...

Error: variable ${AZURE_SUBSCRIPTION_ID} not set

configure-values.sh missing AZURE_SUBSCRIPTION_ID, fix this bug.

* Update configure-values.sh

fix configure-values.sh missing AZURE_SUBSCRIPTION_ID

* Update hack/deploy/configure-values.sh

---------

Co-authored-by: Alex Leites <18728999+tallaxes@users.noreply.github.com>