Update configure-values.sh
chmod +x ./configure-values.sh && ./configure-values.sh ${CLUSTER_NAME} ${RG} karpenter-sa karpentermsi
Configuring karpenter-values.yaml for cluster karpenter in resource group karpenter ...

Error: variable ${AZURE_SUBSCRIPTION_ID} not set

configure-values.sh missing AZURE_SUBSCRIPTION_ID, fix this bug.